[[redirects]]
  from = "/typescript/:page"
  to = "/typescript/index.html"
  status = 200

# [[headers]]
#   # Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     Content-Security-Policy = "frame-ancestors https://www.facebook.com"

#     # Multi-key header rules are expressed with multi-line strings.
#     Link = '''
#     </assets/css/base.css>; rel=preload; as=style, \
#     </assets/css/base2.css>; rel=preload; as=style, \
#     </assets/css/base3.css>; rel=preload; as=style'''

#     # Basic-Auth allows you to password protect your whole site.
#     # This feature may not be available on all plans.
#     Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"
