[build]
  command = "yarn build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/typescript"
  to = "/typescript/0"
  status = 302
[[redirects]]
  from = "/typescript/*"
  to = "https://slides-before-2019-04.netlify.com/typescript/:splat"
  status = 200

[[redirects]]
  from = "/cdk"
  to = "/cdk/0"
  status = 302
[[redirects]]
  from = "/cdk/*"
  to = "https://2019-05-01-cdk.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/ts-subtype"
  to = "/ts-subtype/index.html"
  status = 301
[[redirects]]
  from = "/ts-subtype/*"
  to = "https://adoring-bhabha-5e8abc.netlify.com/:splat"
  status = 200
